
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookReserveService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookReserveService {


    /**
     * 
     * @param arg0
     * @return
     *     returns client.User
     */
    @WebMethod(operationName = "ReserveBooks")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReserveBooks", targetNamespace = "http://service/", className = "client.ReserveBooks")
    @ResponseWrapper(localName = "ReserveBooksResponse", targetNamespace = "http://service/", className = "client.ReserveBooksResponse")
    @Action(input = "http://service/BookReserveService/ReserveBooksRequest", output = "http://service/BookReserveService/ReserveBooksResponse")
    public User reserveBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
