
package client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderCheck", targetNamespace = "http://service2/", wsdlLocation = "http://localhost:8082/CheckOrderService?wsdl")
public class OrderCheck
    extends Service
{

    private final static URL ORDERCHECK_WSDL_LOCATION;
    private final static WebServiceException ORDERCHECK_EXCEPTION;
    private final static QName ORDERCHECK_QNAME = new QName("http://service2/", "OrderCheck");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/CheckOrderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERCHECK_WSDL_LOCATION = url;
        ORDERCHECK_EXCEPTION = e;
    }

    public OrderCheck() {
        super(__getWsdlLocation(), ORDERCHECK_QNAME);
    }

    public OrderCheck(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERCHECK_QNAME, features);
    }

    public OrderCheck(URL wsdlLocation) {
        super(wsdlLocation, ORDERCHECK_QNAME);
    }

    public OrderCheck(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERCHECK_QNAME, features);
    }

    public OrderCheck(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderCheck(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckOrderService
     */
    @WebEndpoint(name = "OrderCheckPort")
    public CheckOrderService getOrderCheckPort() {
        return super.getPort(new QName("http://service2/", "OrderCheckPort"), CheckOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckOrderService
     */
    @WebEndpoint(name = "OrderCheckPort")
    public CheckOrderService getOrderCheckPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service2/", "OrderCheckPort"), CheckOrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERCHECK_EXCEPTION!= null) {
            throw ORDERCHECK_EXCEPTION;
        }
        return ORDERCHECK_WSDL_LOCATION;
    }

}
